[project]
name = "travel-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sunub", email = "bsc5672@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.15.0",
    "bitsandbytes>=0.50.2",
    "datasets>=5.0.1",
    "evaluate>=0.4.6",
    "peft>=0.21.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "safetensors>=0.8.0",
    "torch>=2.14.0",
    "transformers>=5.17.0",
    "trl>=1.14.0",
    "wandb>=0.30.0",
]

[project.scripts]
travel-planner = "travel_planner:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
