"""tripadvisor_reviews.xlsx 실제 리뷰 146건의 라벨 초안.

Claude가 번역된 리뷰 원문을 읽고 라벨링 가이드라인 3·4절에 맞춰 작성했다. 사람이 원문과 대조하기 전이므로 Silver다.
키는 xlsx `Reviews` 시트의 0부터 센 행 번호이고, 값은 (traveler_context, [(aspect, attribute, sentiment, evidence), ...])이다.
리뷰가 이 프로젝트의 aspect로 말하는 내용이 없으면 aspects를 비운다 (모델이 억지 라벨을 만들지 않는지 재는 음성 예시).
"""

P, N, U = "positive", "negative", "neutral"

DRAFT: dict[int, tuple[list[str], list[tuple[str, str, str, str]]]] = {
    0: ([], [("room_size", "average", U, "객실 크기는 보통 수준이고 너무 작지는 않습니다")]),
    1: ([], [("cleanliness", "clean", P, "객실은 깨끗하고 넓었지만"), ("room_size", "spacious", P, "객실은 깨끗하고 넓었지만"),
             ("view_quality", "poor", N, "창문 밖으로 다른 건물의 벽만 보였습니다"),
             ("staff_service", "unfriendly", N, "하우스키퍼가 투숙객인 저희를 먼저 내려보내 주지 않고")]),
    2: ([], [("staff_service", "friendly", P, "직원들은 친절하고 도움이 되었지만"), ("cleanliness", "dirty", N, "청결 상태가 아쉬웠습니다"),
             ("room_condition", "worn", N, "커튼도 임시로 수선한 흔적이 있었습니다")]),
    3: ([], [("food_quality", "good", P, "음식과 분위기가 꽤 좋았고"), ("atmosphere", "good", P, "음식과 분위기가 꽤 좋았고"),
             ("staff_service", "friendly", P, "직원들도 친절했습니다")]),
    4: ([], [("food_quality", "poor", N, "제가 식당에서 먹어 본 음식 중 손꼽히게 끔찍했습니다")]),
    5: ([], [("food_quality", "good", P, "음식은 맛있고 따뜻하며 신선했습니다"), ("freshness", "fresh", P, "음식은 맛있고 따뜻하며 신선했습니다"),
             ("serving_speed", "fast", P, "서비스도 훌륭하고 빨랐습니다"), ("atmosphere", "good", P, "분위기는 조용하고 편안했고"),
             ("noise_level", "quiet", P, "분위기는 조용하고 편안했고")]),
    6: ([], [("view_quality", "good", P, "뷰가 너무 좋았습니다ㅎㅎㅎ"), ("cleanliness", "clean", P, "객실도 너무 깨끗하고"),
             ("staff_service", "friendly", P, "프론트직원분들도\n친절하셨습니다")]),
    7: ([], [("cleanliness", "dirty", N, "첫 객실은 너무 칙칙하고 더러워서 방을 바꿔야 했고"), ("bed_comfort", "uncomfortable", N, "매트리스는 매우 불편했고")]),
    8: ([], [("room_size", "spacious", P, "객실이 넓어서 쓰기에 아주 만족스러웠습니다"), ("view_quality", "good", P, "사우나와 찜질방 뷰가 최고 였습니다"),
             ("amenities", "available", U, "함께 있는 사우나와 찜질방")]),
    9: ([], [("atmosphere", "good", P, "미친 분위기에 친절한 서비스"), ("staff_service", "friendly", P, "친절한 서비스"),
             ("food_quality", "good", P, "안주의 맛도 완벽하고")]),
    10: ([], [("food_quality", "good", P, "제 인생에서 이탈리아 밖에서 먹어 본 피자 중 최고였습니다"),
              ("staff_service", "friendly", P, "매우 친절한 한국인 청년이었고")]),
    11: ([], [("food_quality", "good", P, "사워도우 도우가 맛있었고"), ("portion", "large", P, "토핑도 넉넉했지만"),
              ("seating_comfort", "uncomfortable", N, "발코니에서는 에어컨 실외기의 뜨거운 바람이 불어옵니다")]),
    12: ([], [("food_quality", "good", P, "피자는 부산에서 먹어 본 것 중 최고였습니다")]),
    13: ([], [("room_size", "cramped", N, "크기는 다소 작은 편이었습니다"), ("staff_service", "friendly", P, "매우 친절하게 맞아 주셨습니다"),
              ("amenities", "available", U, "생수와 수건 등 기본적인 비품은 제공됩니다")]),
    14: ([], [("cleanliness", "clean", P, "호텔은 기본적인 수준이지만 깨끗했습니다"), ("bed_comfort", "comfortable", P, "객실 침대는 편안했고"),
              ("bathroom_quality", "good", P, "레인샤워가 있는 욕실도 아주 좋았습니다")]),
    15: ([], [("view_quality", "good", P, "전망이 훌륭했습니다"), ("bed_comfort", "comfortable", P, "침대는 매우 편안하고 크기도 충분해 숙면에 문제가 없었습니다"),
              ("bathroom_quality", "good", P, "욕실도 넉넉하고 잘 설계되어 있었습니다"),
              ("room_condition", "worn", N, "샤워기 거치대 하나가 금이 가 있어 샤워헤드가 떨어질 뻔했습니다"),
              ("breakfast_quality", "good", P, "조식은 특히 좋았습니다"), ("staff_service", "friendly", P, "프런트 직원들도 친절했고"),
              ("amenities", "available", U, "슬리퍼, 가운, 헤어드라이어가 제공됩니다")]),
    16: ([], []),
    17: ([], []),
    18: ([], []),
    19: ([], [("staff_service", "friendly", P, "정말 잘 챙겨 주셨고")]),
    20: ([], [("noise_level", "noisy", N, "거리가 매우 활기차기 때문에 일찍 자고 싶은 분에게는 적합하지 않을 수 있습니다"),
              ("view_quality", "good", P, "바다와 다리 전망은 훌륭하고")]),
    21: ([], [("room_size", "cramped", N, "객실은 작았지만"), ("cleanliness", "clean", P, "객실은 매우 깨끗했고"),
              ("bed_comfort", "comfortable", P, "침대와 베개 모두 메모리폼이라 숙면을 취하기 좋았습니다"),
              ("amenities", "available", U, "객실에 휴대전화 충전기를 비치해 둔 점이 특히 인상적이었습니다"),
              ("staff_service", "friendly", P, "아침에 객실 문 밖에 조식 가방을 걸어 준 직원들에게도 감사드립니다")]),
    22: ([], [("view_quality", "good", P, "해변 바로 앞 전망과 위치가 정말 좋았습니다"), ("cleanliness", "clean", P, "호텔은 깨끗하고 편안했습니다"),
              ("bed_comfort", "comfortable", P, "침대도 매우 편안했고")]),
    23: ([], []),
    24: ([], []),
    25: ([], []),
    26: ([], [("room_size", "cramped", N, "객실은 꽤 작았지만"), ("cleanliness", "clean", P, "깨끗하고 편안했고"),
              ("amenities", "available", U, "필요한 것은 모두 제공되었고")]),
    27: ([], [("scenery", "sea", P, "모래가 정말 부드럽고 고운 아름다운 해변입니다"), ("scenery", "night_view", P, "밤에는 다리에 불이 들어와 꼭 한 번 볼 만합니다")]),
    28: ([], [("weather_sensitivity", "high", U, "날씨가 좋지 않아 보지 못했습니다")]),
    29: ([], []),
    30: ([], [("stay_duration", "long", U, "여러 휴게 공간과 야외 족욕, 라면을 먹는 데 약 3시간을 보냈고"),
              ("rest_facilities", "sufficient", P, "여러 휴게 공간")]),
    31: ([], []),
    32: ([], []),
    33: ([], [("room_condition", "worn", N, "지금은 많이 낡아 보입니다"), ("cleanliness", "dirty", N, "카펫에는 얼룩이 있으며"),
              ("amenities", "unavailable", N, "편의시설 측면에서는 매우 부족합니다")]),
    34: ([], [("bed_comfort", "comfortable", P, "침대는 편안합니다"), ("staff_service", "unfriendly", N, "직원 태도가 매우 좋지 않았습니다"),
              ("amenities", "unavailable", N, "비누, 샴푸, 컨디셔너가 제공되지 않았고"),
              ("bathroom_quality", "poor", N, "3인실에 수건걸이가 하나뿐인 것은 너무 불편했습니다"),
              ("room_condition", "worn", N, "지금은 많이 낡은 느낌입니다"), ("cleanliness", "dirty", N, "지금은 회색빛으로 더러워짐")]),
    35: ([], [("view_quality", "good", P, "테라스 뷰 맛집이고"), ("breakfast_quality", "good", P, "조식도 작은 뷔페지만 있을만한 메뉴는 다 있음")]),
    36: ([], [("view_quality", "good", P, "객실 전망이 정말 훌륭했습니다"), ("bathroom_quality", "good", P, "샤워실과 화장실이 분리되어 있어 좋았습니다"),
              ("breakfast_quality", "average", U, "조식은 시리얼, 빵과 일부 한식이 있는 평범한 수준이었습니다"),
              ("room_size", "cramped", N, "객실은 두 사람이 쓰기에 딱 맞을 정도로 작아")]),
    37: ([], [("staff_service", "friendly", P, "친절하고 깨끗합니다"), ("cleanliness", "clean", P, "친절하고 깨끗합니다"),
              ("room_size", "spacious", P, "객실 공간도 부족함 없이 넉넉합니다")]),
    38: ([], [("staff_service", "unfriendly", N, "체크인할 때 중국어를 사용한다는 이유로 직원에게 차별을 받았다고 느꼈습니다")]),
    39: ([], [("staff_service", "friendly", P, "모든 직원들이 매우 세심하고 친절했고"), ("cleanliness", "clean", P, "호텔도 매우 깨끗하고 편안했습니다")]),
    40: ([], [("cleanliness", "clean", P, "현대적이고 깨끗해서"), ("staff_service", "friendly", P, "직원들은 도움이 되었고 친절했으며"),
              ("bathroom_quality", "poor", N, "고령자가 샤워하기에는 안전하지 않아 보였습니다"), ("amenities", "available", U, "스파도 즐겼는데")]),
    41: ([], [("atmosphere", "good", P, "내부는 깔끔하고 일본 정통 분위기가 나는 공간으로 꾸며졌더라고요"), ("cleanliness", "clean", P, "내부는 깔끔하고"),
              ("food_quality", "good", P, "정말 맛있더라고요")]),
    42: ([], [("portion", "large", P, "여전히 푸짐하고"), ("food_quality", "good", P, "정말 맛있습니다"), ("freshness", "fresh", P, "신선한것만 쓰셔셔")]),
    43: ([], [("food_quality", "good", P, "바삭하고 재료가 신선해서 아주 맛있었어요"), ("freshness", "fresh", P, "재료가 신선해서")]),
    44: ([], [("food_quality", "good", P, "지금까지 먹어 본 호텔 조식 중 가장 좋았습니다")]),
    45: ([], []),
    46: ([], [("stay_duration", "medium", U, "전체를 둘러보는 데 약 1시간 정도 걸렸습니다")]),
    47: ([], []),
    48: ([], []),
    49: ([], []),
    50: ([], [("stay_duration", "medium", U, "약 1시간 30분 정도 잡으면 됩니다")]),
    51: ([], [("slope_stairs", "high", N, "계단이 약 70구간 정도 있어 무릎이 좋지 않다면 어렵습니다"),
              ("scenery", "sea", P, "바다와 부산의 멋진 전망을 볼 수 있는 훌륭한 트레일입니다")]),
    52: ([], []),
    53: ([], []),
    54: ([], [("atmosphere", "good", P, "따뜻하고 겸손한 분위기를 풍기며"), ("food_quality", "good", P, "예쁘게 담긴 맛있는 수제 음식")]),
    55: ([], [("atmosphere", "good", P, "박지민을 기리는 분위기도 훌륭합니다")]),
    56: ([], [("weather_sensitivity", "high", U, "뜨거운 햇볕을 피해"), ("scenery", "sea", P, "바다 전망이 끝없이 이어지는 멋진 데크길이었고")]),
    57: ([], [("stay_duration", "short", U, "약 30분 정도로 오래 걸리지 않으며")]),
    58: ([], [("activity_variety", "many", P, "볼거리가 많습니다"), ("walking_burden", "low", P, "여름에는 그늘 덕분에 걷기 좋았습니다")]),
    59: ([], []),
    60: ([], [("cleanliness", "clean", P, "가격도 합리적이고 깨끗합니다"), ("view_quality", "good", P, "오션뷰 광안대교와 바다가 다 보입니다"),
              ("staff_service", "friendly", P, "직원들도 친절합니다"), ("amenities", "available", U, "건물에 레스토랑도 있고")]),
    61: ([], []),
    62: ([], []),
    63: ([], []),
    64: ([], []),
    65: ([], []),
    66: ([], [("food_quality", "good", P, "점심도 아주 맛있었습니다"), ("portion", "large", P, "양도 넉넉했습니다")]),
    67: ([], []),
    68: (["couple"], [("food_quality", "good", P, "모두 정말 훌륭했습니다"),
                      ("atmosphere", "good", P, "타이포그래피와 재미있는 그래픽, 인테리어 디자인도 최고였습니다")]),
    69: ([], []),
    70: ([], [("food_quality", "good", P, "대박 맛있어요"), ("staff_service", "friendly", P, "직원분들 친절해요"), ("cleanliness", "clean", P, "매장도 깔끔하고")]),
    71: ([], [("food_quality", "good", P, "맛있는 젤라또를 먹으니 정말 시원하고 상쾌했습니다")]),
    72: ([], [("staff_service", "friendly", P, "직원들이 매우 친절했고"), ("food_quality", "good", P, "고기 품질도 아주 좋았습니다")]),
    73: ([], [("staff_service", "friendly", P, "직원분들이 굉장히 친절하게 맞아주시고"), ("food_quality", "good", P, "식사 메뉴도 기대 이상이었어요"),
              ("atmosphere", "good", P, "매장 분위기도 과하게 시끄럽지 않고 적당히 활기 있는 느낌"), ("noise_level", "moderate", P, "과하게 시끄럽지 않고")]),
    74: ([], [("food_quality", "good", P, "훌륭한 이탈리안 레스토랑이고 음식이 맛있습니다"), ("staff_service", "friendly", P, "셰프이자 사장님도 매우 친절했고")]),
    75: ([], [("food_quality", "good", P, "음식도 아주 맛있고 든든했습니다"), ("staff_service", "friendly", P, "알레르기가 있는 사람도 있는지 먼저 물어봐 주었습니다")]),
    76: ([], [("food_quality", "good", P, "새우 오일 파스타를 주문했는데 정말 맛있었고"), ("staff_service", "friendly", P, "서비스로 마늘빵과 와인 한 잔을 주셔서 정말 좋았습니다")]),
    77: ([], [("food_quality", "good", P, "맛이 훌륭하고")]),
    78: ([], [("food_quality", "good", P, "젤라또 쫀득쫀득하고 맛있어요")]),
    79: ([], [("food_quality", "good", P, "국물은 깊고 진하며 속을 편안하게 해 주는 맛이었습니다")]),
    80: ([], [("food_quality", "good", P, "시그니처 소고기국밥이 정말 훌륭했습니다"), ("portion", "large", P, "양도 넉넉합니다")]),
    81: ([], [("food_quality", "good", P, "한식 소고기국밥도 정말 맛있습니다"), ("portion", "large", P, "소고기가 많이 들어 있고")]),
    82: ([], []),
    83: ([], []),
    84: (["family_with_kids"], [("weather_sensitivity", "low", U, "깨끗한 실내 공간이라")]),
    85: ([], [("food_quality", "good", P, "숙성회맛이 너무 좋습니다"), ("atmosphere", "good", P, "분위기와 숙성회맛이 너무 좋습니다")]),
    86: ([], [("food_quality", "good", P, "부산에서 먹어본 사시미중에 가장 훌륭한 곳")]),
    87: ([], [("food_quality", "good", P, "저에게 최고의 맛을 선사 하였습니다")]),
    88: ([], [("atmosphere", "good", P, "분위기 좋고 맛도 좋아서"), ("food_quality", "good", P, "새우에 크림 듬뿍인데 느끼하지 않고 고소해요"),
              ("portion", "large", P, "치즈+토핑 다 넉넉하게 들어가서"), ("parking_availability", "available", P, "상가 주차 가능해서"),
              ("parking_experience", "easy", P, "차 가지고 가기도 편했고")]),
    89: ([], [("food_quality", "good", P, "제가 지금까지 먹어 본 피자 중 최고였습니다")]),
    90: ([], [("room_condition", "well_kept", P, "방 컨디션도 굿"), ("view_quality", "good", P, "뷰도 굿")]),
    91: ([], [("view_quality", "good", P, "광안대교가 보이는 뷰에"), ("cleanliness", "clean", P, "룸컨디션도 깨끗하고 너무 좋았습니다")]),
    92: ([], [("cleanliness", "clean", P, "너무너무 깔끔하고"), ("room_size", "spacious", P, "객실도 넓고"), ("view_quality", "good", P, "창밖으로 넓은 바다도 보여서")]),
    93: ([], [("serving_speed", "slow", N, "서비스가 느리고"), ("portion", "large", P, "양은 매우 크지만")]),
    94: ([], [("food_quality", "good", P, "훌륭한 팬케이크를 먹고 싶다면 놓치지 마세요")]),
    95: ([], [("waiting_time", "long", U, "20분 정도 기다렸습니다"), ("food_quality", "average", U, "전반적으로 무난했습니다")]),
    96: ([], [("food_quality", "good", P, "초밥과 치킨 모두 품질이 좋았고")]),
    97: ([], []),
    98: ([], [("view_quality", "good", P, "광안리해변 전망이 정말 멋집니다"), ("room_size", "cramped", N, "객실은 아담하지만"),
              ("cleanliness", "clean", P, "매우 깔끔했고"), ("staff_service", "friendly", P, "직원들도 아주 친절했습니다")]),
    99: ([], [("room_size", "spacious", P, "객실은 밝고 넓었으며"), ("staff_service", "friendly", P, "직원들도 매우 밝게 웃으며 친절하게 맞아 주었습니다"),
              ("amenities", "available", U, "필요한 것이 모두 갖춰져 있었습니다")]),
    100: ([], [("food_quality", "good", P, "광안리 최고의 파스타 맛집이었습니다~"), ("staff_service", "friendly", P, "사장님도 너무 친절하시고")]),
    101: ([], [("atmosphere", "good", P, "음악과 분위기 인테리어 모든 조화가 잘 이루어 졌으며"), ("food_quality", "good", P, "음식 또 한 너무 맛있었어요"),
               ("staff_service", "friendly", P, "사장님도 너무 친절 하셔용")]),
    102: ([], []),
    103: ([], []),
    104: (["couple"], [("atmosphere", "good", P, "넓고 세련된 분위기에 분수대랑 조명이 어우러져 있어서"), ("food_quality", "good", P, "커피 맛도 깔끔하고")]),
    105: ([], [("staff_service", "friendly", P, "친철하시고"), ("food_quality", "good", P, "너무 맛있었어요!!")]),
    106: ([], [("food_quality", "good", P, "맛있고 친절해요"), ("staff_service", "friendly", P, "친절해요")]),
    107: ([], [("cleanliness", "dirty", N, "객실도 더러웠습니다")]),
    108: ([], []),
    109: ([], []),
    110: ([], []),
    111: ([], []),
    112: (["couple"], [("room_size", "spacious", P, "객실은 매우 넓었고"), ("bathroom_quality", "good", P, "욕실도 넓었으며 자쿠지가 있었습니다"),
                       ("bathroom_quality", "poor", N, "샤워 유리문과 바닥 사이에 틈이 있어 샤워할 때 물이 밖으로 샐 수 있으니 주의해야 합니다"),
                       ("staff_service", "friendly", P, "직원들은 매우 친절하고 환영해 주었습니다"),
                       ("bed_comfort", "comfortable", P, "단단한 침대를 좋아해서 둘이 쓰기에 매우 편했습니다"),
                       ("amenities", "available", U, "화장대에는 헤어드라이어와 고데기가 모두 있어")]),
    113: (["friends"], [("food_quality", "good", P, "회를 맛있게 먹었습니다")]),
    114: ([], [("atmosphere", "good", P, "세련된 인테리어와 디테일이 인상적입니다"), ("staff_service", "friendly", P, "사장님은 정말 친절하고 영어도 잘합니다")]),
    115: ([], [("cleanliness", "clean", P, "매우 깨끗한 식당이고"), ("food_quality", "good", P, "음식도 맛있습니다")]),
    116: ([], [("food_quality", "good", P, "인도 음식이 정말 맛있고"), ("freshness", "fresh", P, "난은 신선하고 완벽하게 구워졌으며"),
               ("staff_service", "friendly", P, "직원들도 친절하고 환영해 주었습니다")]),
    117: ([], [("room_size", "cramped", N, "객실은 꽤 작았지만"), ("amenities", "available", U, "간단한 취사가 가능한 시설이 괜찮게 갖춰져 있었습니다"),
               ("amenities", "unavailable", N, "큰 목욕수건이 없다는 점이었습니다")]),
    118: ([], [("scenery", "river", P, "물가 전망도 훌륭합니다")]),
    119: ([], [("stay_duration", "short", U, "건물 자체를 보는 데는 10분 정도면 충분합니다")]),
    120: ([], [("staff_service", "unfriendly", N, "도움을 주려는 의지도 크게 느껴지지 않았습니다"), ("cleanliness", "dirty", N, "도착했을 때부터 객실이 더러웠고"),
               ("bathroom_quality", "poor", N, "샤워할 때마다 욕실이 물바다가 되었으며"), ("room_condition", "well_kept", P, "객실도 예쁘며 최근 리모델링한 듯하지만"),
               ("amenities", "unavailable", N, "Wi-Fi는 작동하지 않았고")]),
    121: ([], [("atmosphere", "good", P, "분위기가 아주 좋은 훌륭한 바입니다"), ("staff_service", "friendly", P, "필요한 것을 세심하게 챙겨 주었습니다"),
               ("food_quality", "good", P, "음식도 먹었는데 맛있고 따뜻하게 나왔습니다"), ("cleanliness", "clean", P, "여자 화장실도 매우 깨끗했습니다")]),
    122: ([], [("food_quality", "good", P, "음식도 아주 맛있었습니다"), ("staff_service", "friendly", P, "매우 친절하게 즉시 응대해 주었습니다"),
               ("atmosphere", "good", P, "분위기도 좋았습니다")]),
    123: ([], [("cleanliness", "dirty", N, "매우 더럽습니다"), ("bathroom_quality", "poor", N, "샤워할 때마다 욕실이 물바다가 됩니다"),
               ("staff_service", "unfriendly", N, "프런트 직원들의 응대가 좋지 않고"), ("amenities", "unavailable", N, "Wi-Fi가 되지 않았습니다")]),
    124: ([], [("food_quality", "poor", N, "피자는 덜 익었고 토마토소스는 너무 묽었습니다"), ("cleanliness", "dirty", N, "머리카락이 4개나 나왔고 파리도 3마리 있었습니다"),
               ("serving_speed", "slow", N, "음식이 나오기까지 웨이터가 한 시간이나 걸렸습니다")]),
    125: ([], [("photo_spots", "good", P, "낮에도 훌륭한 사진 명소지만 특히 밤에 멋집니다"), ("scenery", "night_view", P, "특히 밤에 멋집니다")]),
    126: (["family_with_kids"], [("scenery", "night_view", P, "이 다리는 꼭 밤에 보길 추천합니다")]),
    127: ([], []),
    128: ([], [("scenery", "sea", P, "스카이워크에서 두 섬을 바라보는 전망은 아름답지만")]),
    129: ([], [("scenery", "sea", P, "부산과 인근 해안의 전망을 볼 수 있습니다")]),
    130: ([], []),
    131: ([], []),
    132: ([], [("food_quality", "good", P, "음식은 정통적이고 맛있습니다"), ("staff_service", "friendly", P, "음식과 서비스 모두 훌륭합니다")]),
    133: ([], [("food_quality", "good", P, "삼계탕이 맛있었습니다"), ("staff_service", "friendly", P, "식당의 친절한 직원분이 매우 잘 응대해 주셨고")]),
    134: ([], [("atmosphere", "good", P, "분위기에서 전통적인 한국 느낌이 물씬 나고"), ("food_quality", "good", P, "음식도 정말 맛있습니다")]),
    135: ([], [("food_quality", "good", P, "고기를 좋아하는 사람에게 아주 좋은 바비큐 립입니다")]),
    136: ([], [("staff_service", "friendly", P, "직원들도 매우 친절하고 배려해 주었습니다"), ("food_quality", "good", P, "음식은 매우 맛있었고")]),
    137: ([], [("staff_service", "friendly", P, "직원도 매우 친절했고 영어도 할 수 있었습니다"), ("food_quality", "good", P, "정말 맛있고 섬세한 맛이어서"),
               ("atmosphere", "good", P, "편안하고 아늑한 분위기입니다")]),
    138: ([], [("food_quality", "good", P, "정말 맛있습니다!!")]),
    139: ([], [("food_quality", "good", P, "정말 맛있었습니다!"), ("portion", "large", P, "다 먹지 못할 정도였습니다")]),
    140: ([], []),
    141: ([], []),
    142: ([], []),
    143: ([], []),
    144: ([], [("food_quality", "good", P, "이 식당이 가장 만족스러웠습니다")]),
    145: (["family_with_kids"], [("food_quality", "good", P, "모두 훌륭했습니다")]),
}
